if(NOT EXISTS "${NOTICE}")
    message(FATAL_ERROR "Third-party notices were not generated")
endif()
file(READ "${NOTICE}" _contents)
foreach(_component IN ITEMS XAIR XAIR_CFG XAIR_SYM ZYDIS ZYCORE Z3)
    if(NOT _contents MATCHES "## ${_component}")
        message(FATAL_ERROR "Third-party notices omit ${_component}")
    endif()
endforeach()
